services:
  flask-app:
    image: arynxd/uws-running-app:{{ app_version }}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app